### ISSUE TITLE
What do we want to eat for breakfast?

### ISSUE THREAD

**Issue by ubuntupoe** [IntroToCode/Spring21_Recipes_Codemates9#1]
## 💬 Discussion topic

Breakfast recipe

## ❗ Potential issues

Pancakes or waffles?

## 👥 People to consult

@DYared15 @yuhsin-cheng 

## 📃 Details

We only have 6 eggs.

**Comment by yuhsin-cheng** [comment]
Pancakes!

**Comment by DYared15** [comment]
Pancakes! 👍

**Comment by ubuntupoe** [comment]
Pancakes it is -- 
Acceptance criteria:
- must include buttermilk
- maple syrup
- eggs, with whites separated and beaten
- bonus points for sour cream

**Comment by ubuntupoe** [comment]
This issue is resolved.
