### ISSUE TITLE
What do we want to eat for dinner?

### ISSUE THREAD

**Issue by DYared15** [IntroToCode/Spring21_Recipes_Codemates9#6]
## 💬 Discussion topic

Dinner Options!

## ❗ Potential issues

Mac and cheese or pizza?

## 👥 People to consult

@ubuntupoe @yuhsin-cheng 

## 📃 Details

Will include a vegan recipe for those with dietary restrictions.
Make sure to use breadcrumbs!

**Comment by ubuntupoe** [comment]
Mac and cheese for sure! 
I'd recommend parsley on top to garnish!

**Comment by yuhsin-cheng** [comment]
Mac and cheese is an amazing idea!

**Comment by yuhsin-cheng** [comment]
Since all decided, let's close this issue.
