### ISSUE TITLE
What do we want to eat for lunch?

### ISSUE THREAD

**Issue by yuhsin-cheng** [IntroToCode/Spring21_Recipes_Codemates9#8]
## 💬 Discussion topic

Healthy or some comfort food?

## ❗ Potential issues

Avocado toast or Fried chicken?

## 👥 People to consult

@DYared15 @ubuntupoe 

## 📃 Details

Text

**Comment by ubuntupoe** [comment]
Avocado toast sounds great!! 🥑

**Comment by DYared15** [comment]
I'd love avocado toast! Let's do that! 👍

**Comment by ubuntupoe** [comment]
This issue is resolved.
